name: GO Package Release


on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        default: "v1.0.0"

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          
          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: 1.21
          
          - run: git tag ${{ github.event.inputs.tag }}

          - name: Create Go Release
            uses: goreleaser/goreleaser-action@v5
            env:
              GITHUB_TOKEN: ${{ secrets.GO_GCE_HEALTH_CHECK_DEPLOY }}
            with:
                version: latest
                args: release --cleanup-previous --rm-dist
